# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

encodeNumAltAlleles <- function(x, ref, alt) {
    .Call('tasselr_encodeNumAltAlleles', PACKAGE = 'tasselr', x, ref, alt)
}

